### ISSUE TITLE
Offsets with landscape bbox

### ISSUE THREAD

**Issue by leplatrem** [kartena/Proj4Leaflet#37] opened 2013-08-23 09:19 UTC
I suppose there is something wrong with `origin` usage for landscape bounding boxes.

With the same array of resolutions in TileCache and Leaflet, Proj4Leaflet works perfectly with portrait bbox, but suffers an offset if bbox is landscape (width>height).

You can find a complete example that demonstrate the problem:
http://mathieu-leplatre.info/media/2013-proj4leaflet/

In the above example, I compute resolutions the same way as TileCache (they are printed out as proof)

Using static resolutions/scale array does not solve the problem.

**Comment by pthorin** [comment] 2017-01-26 09:06
Is this still an issue?

**Comment by perliedman** [comment] 2017-11-12 12:17
Closing as we don't have any information to act on here, and the issue is really old.

Happy to re-open if this is still an issue and we can get example code for recent versions.

**Closed by perliedman** 2017-11-12 12:17 UTC
