### ISSUE TITLE
Cannot properly restrict bounds in polar projection

### ISSUE THREAD

**Issue by duckontheweb** [kartena/Proj4Leaflet#122] opened 2016-09-02 00:44 UTC
Passing `maxBounds` in the map options sometimes does not lead to the expected results in polar projections. In [this example](http://jsfiddle.net/mq52r6zj/7/) the `maxBounds` are the same as the initial bounds, but trying to zoom into an area on the left of the map is unallowed.

This is probably to do with the fact that Leaflet handles restricting the bounds entirely in the lat/lon space and not in the projected space (see the [`L.Map._limitOffset`](https://github.com/Leaflet/Leaflet/blob/197f9d43b7bbc73c0492bf62cd666a5a98038098/src/map/Map.js#L774-L782) method for an example of this. These methods would probably need to be overwritten to manage these restrictions in a projected space in order to correct this.

**Comment by jduckworth** [comment] 2016-09-02 00:48
... I'll work on some possible solutions for this.

**Comment by perliedman** [comment] 2016-09-02 13:35
Yes, have been thinking about this problem, and I agree with your conclusion that handling bounds etc in lat/lng-space doesn't work very well for polar projections.

I remember that I at some point looked at adding a `fitBounds` equivalent that worked in projected space, and it looked like it could be possible. Doing the same for bounds might be trickier without ripping apart Leaflet's internals, but that's just me guessing since I haven't really checked.

**Comment by perliedman** [comment] 2017-11-12 11:39
Looking at this issue again, I agree that it's a valid problem that needs to be addressed to make polar projections work well in Leaflet, but the problem is in Leaflet and not in Proj4Leaflet, as I see it.

So, I'm closing this, since I don't think it's something that can be addressed within the Proj4Leaflet project.

Possibly related is https://github.com/Leaflet/Leaflet/issues/5617, which is fixed in Leaflet's `master` branch, but has not been released yet when I'm writing this.

**Closed by perliedman** 2017-11-12 11:39 UTC

**Comment by duckontheweb** [comment] 2017-11-12 13:34
I agree @perliedman, I think this is more appropriate as a change on Leaflet. I'll check out the latest changes on master and see if it makes sense to put in an issue there. Thanks!
